PROPOSER_SIDE_NAME: Men
RESPONDER_SIDE_NAME: Women

NUMBER_OF_PROPOSERS: 2 
NUMBER_OF_RESPONDERS: 2

PREFERENCE_TYPE: input # random or input are valid

LOG_FILE_NAME: logs.log # will be saved under logs folder

# REQUIRED IF PREFERENCE_TYPE IS INPUT
# SUFFICES TO LIST ONLY ACCEPTABLES
PROPOSERS:
  will: # will's preferences are 1. april, 2. summer, 3. himself
  - april
  - summer
  hampton: # hampton's preferences are 1. summer, 2. himself, 3. april
  - summer
RESPONDERS:
  april: # april's preferences are 1. will, 2. herself, 3. hampton
  - will
  summer: # summer's preferences are 1. will, 2. hampton, 3. herself
  - will
  - hampton
