proposer_side_name: man
responder_side_name: woman
number_of_proposers: 5
number_of_responders: 7
preference_type: random # only random is valid for now, custom input will be implemented later
log_file: logs.log # will be saved in logs folder
